version: '3.9'

services:
  pgbd:
    image: postgres:15.5-bullseye
    restart: always
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: food
      POSTGRES_PASSWORD: qazwsx
    ports:
      - 5434:5432
    volumes:
      - ./data:/var/lib/postgresql/data